/*
 * Copyright (c) 2018, Tomas Slusny <slusnucky@gmail.com>
 * Copyright (c) 2018, Seth <Sethtroll3@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package meteor.game

import com.google.common.collect.HashMultimap
import com.google.common.collect.Multimap
import net.runelite.api.ItemID

/**
 * Converts untradeable items to it's tradeable counterparts
 */
enum class ItemMapping(val tradeableItem: Int, val untradeable: Boolean, val quantity: Long, vararg val untradableItems: Int) {
    // Barrows equipment
    ITEM_AHRIMS_HOOD(ItemID.AHRIMS_HOOD, ItemID.AHRIMS_HOOD_25, ItemID.AHRIMS_HOOD_50, ItemID.AHRIMS_HOOD_75, ItemID.AHRIMS_HOOD_100), ITEM_AHRIMS_ROBETOP(ItemID.AHRIMS_ROBETOP, ItemID.AHRIMS_ROBETOP_25, ItemID.AHRIMS_ROBETOP_50, ItemID.AHRIMS_ROBETOP_75,
            ItemID.AHRIMS_ROBETOP_100),
    ITEM_AHRIMS_ROBEBOTTOM(ItemID.AHRIMS_ROBESKIRT, ItemID.AHRIMS_ROBESKIRT_25, ItemID.AHRIMS_ROBESKIRT_50,
            ItemID.AHRIMS_ROBESKIRT_75, ItemID.AHRIMS_ROBESKIRT_100),
    ITEM_AHRIMS_STAFF(ItemID.AHRIMS_STAFF, ItemID.AHRIMS_STAFF_25, ItemID.AHRIMS_STAFF_50, ItemID.AHRIMS_STAFF_75,
            ItemID.AHRIMS_STAFF_100),
    ITEM_KARILS_COIF(ItemID.KARILS_COIF, ItemID.KARILS_COIF_25, ItemID.KARILS_COIF_50, ItemID.KARILS_COIF_75, ItemID.KARILS_COIF_100), ITEM_KARILS_LEATHERTOP(ItemID.KARILS_LEATHERTOP, ItemID.KARILS_LEATHERTOP_25, ItemID.KARILS_LEATHERTOP_50,
            ItemID.KARILS_LEATHERTOP_75, ItemID.KARILS_LEATHERTOP_100),
    ITEM_KARILS_LEATHERSKIRT(ItemID.KARILS_LEATHERSKIRT, ItemID.KARILS_LEATHERSKIRT_25, ItemID.KARILS_LEATHERSKIRT_50,
            ItemID.KARILS_LEATHERSKIRT_75, ItemID.KARILS_LEATHERSKIRT_100),
    ITEM_KARILS_CROSSBOW(ItemID.KARILS_CROSSBOW, ItemID.KARILS_CROSSBOW_25, ItemID.KARILS_CROSSBOW_50, ItemID.KARILS_CROSSBOW_75,
            ItemID.KARILS_CROSSBOW_100),
    ITEM_DHAROKS_HELM(ItemID.DHAROKS_HELM, ItemID.DHAROKS_HELM_25, ItemID.DHAROKS_HELM_50, ItemID.DHAROKS_HELM_75,
            ItemID.DHAROKS_HELM_100),
    ITEM_DHAROKS_PLATEBODY(ItemID.DHAROKS_PLATEBODY, ItemID.DHAROKS_PLATEBODY_25, ItemID.DHAROKS_PLATEBODY_50,
            ItemID.DHAROKS_PLATEBODY_75, ItemID.DHAROKS_PLATEBODY_100),
    ITEM_DHAROKS_PLATELEGS(ItemID.DHAROKS_PLATELEGS, ItemID.DHAROKS_PLATELEGS_25, ItemID.DHAROKS_PLATELEGS_50,
            ItemID.DHAROKS_PLATELEGS_75, ItemID.DHAROKS_PLATELEGS_100),
    ITEM_DHARKS_GREATEAXE(ItemID.DHAROKS_GREATAXE, ItemID.DHAROKS_GREATAXE_25, ItemID.DHAROKS_GREATAXE_50,
            ItemID.DHAROKS_GREATAXE_75, ItemID.DHAROKS_GREATAXE_100),
    ITEM_GUTHANS_HELM(ItemID.GUTHANS_HELM, ItemID.GUTHANS_HELM_25, ItemID.GUTHANS_HELM_50, ItemID.GUTHANS_HELM_75,
            ItemID.GUTHANS_HELM_100),
    ITEM_GUTHANS_PLATEBODY(ItemID.GUTHANS_PLATEBODY, ItemID.GUTHANS_PLATEBODY_25, ItemID.GUTHANS_PLATEBODY_50,
            ItemID.GUTHANS_PLATEBODY_75, ItemID.GUTHANS_PLATEBODY_100),
    ITEM_GUTHANS_CHAINSKIRT(ItemID.GUTHANS_CHAINSKIRT, ItemID.GUTHANS_CHAINSKIRT_25, ItemID.GUTHANS_CHAINSKIRT_50,
            ItemID.GUTHANS_CHAINSKIRT_75, ItemID.GUTHANS_CHAINSKIRT_100),
    ITEM_GUTHANS_WARSPEAR(ItemID.GUTHANS_WARSPEAR, ItemID.GUTHANS_WARSPEAR_25, ItemID.GUTHANS_WARSPEAR_50,
            ItemID.GUTHANS_WARSPEAR_75, ItemID.GUTHANS_WARSPEAR_100),
    ITEM_TORAGS_HELM(ItemID.TORAGS_HELM, ItemID.TORAGS_HELM_25, ItemID.TORAGS_HELM_50, ItemID.TORAGS_HELM_75, ItemID.TORAGS_HELM_100), ITEM_TORAGS_PLATEBODY(ItemID.TORAGS_PLATEBODY, ItemID.TORAGS_PLATEBODY_25, ItemID.TORAGS_PLATEBODY_50,
            ItemID.TORAGS_PLATEBODY_75, ItemID.TORAGS_PLATEBODY_100),
    ITEM_TORAGS_PLATELEGS(ItemID.TORAGS_PLATELEGS, ItemID.TORAGS_PLATELEGS_25, ItemID.TORAGS_PLATELEGS_50,
            ItemID.TORAGS_PLATELEGS_75, ItemID.TORAGS_PLATELEGS_100),
    ITEM_TORAGS_HAMMERS(ItemID.TORAGS_HAMMERS, ItemID.TORAGS_HAMMERS_25, ItemID.TORAGS_HAMMERS_50, ItemID.TORAGS_HAMMERS_75,
            ItemID.TORAGS_HAMMERS_100),
    ITEM_VERACS_HELM(ItemID.VERACS_HELM, ItemID.VERACS_HELM_25, ItemID.VERACS_HELM_50, ItemID.VERACS_HELM_75, ItemID.VERACS_HELM_100), ITEM_VERACS_BRASSARD(ItemID.VERACS_BRASSARD, ItemID.VERACS_BRASSARD_25, ItemID.VERACS_BRASSARD_50, ItemID.VERACS_BRASSARD_75,
            ItemID.VERACS_BRASSARD_100),
    ITEM_VERACS_PLATESKIRT(ItemID.VERACS_PLATESKIRT, ItemID.VERACS_PLATESKIRT_25, ItemID.VERACS_PLATESKIRT_50,
            ItemID.VERACS_PLATESKIRT_75, ItemID.VERACS_PLATESKIRT_100),
    ITEM_VERACS_FLAIL(ItemID.VERACS_FLAIL, ItemID.VERACS_FLAIL_25, ItemID.VERACS_FLAIL_50, ItemID.VERACS_FLAIL_75,
            ItemID.VERACS_FLAIL_100),  // Dragon equipment ornament kits
    ITEM_DRAGON_SCIMITAR(ItemID.DRAGON_SCIMITAR, ItemID.DRAGON_SCIMITAR_OR), ITEM_DRAGON_SCIMITAR_ORNAMENT_KIT(ItemID.DRAGON_SCIMITAR_ORNAMENT_KIT, ItemID.DRAGON_SCIMITAR_OR), ITEM_DRAGON_DEFENDER(ItemID.DRAGON_DEFENDER_ORNAMENT_KIT, ItemID.DRAGON_DEFENDER_T), ITEM_DRAGON_PICKAXE(ItemID.DRAGON_PICKAXE, ItemID.DRAGON_PICKAXE_12797, ItemID.DRAGON_PICKAXE_OR,
            ItemID.DRAGON_PICKAXE_OR_25376),
    ITEM_DRAGON_PICKAXE_OR(ItemID.ZALCANO_SHARD, ItemID.DRAGON_PICKAXE_OR), ITEM_DRAGON_AXE(ItemID.DRAGON_AXE, ItemID.DRAGON_AXE_OR), ITEM_DRAGON_HARPOON(ItemID.DRAGON_HARPOON, ItemID.DRAGON_HARPOON_OR), ITEM_INFERNAL_PICKAXE_OR(ItemID.INFERNAL_PICKAXE, ItemID.INFERNAL_PICKAXE_OR), ITEM_INFERNAL_PICKAXE_OR_UNCHARGED(ItemID.INFERNAL_PICKAXE_UNCHARGED, ItemID.INFERNAL_PICKAXE_UNCHARGED_25369), ITEM_INFERNAL_AXE_OR(ItemID.INFERNAL_AXE, ItemID.INFERNAL_AXE_OR), ITEM_INFERNAL_AXE_OR_UNCHARGED(ItemID.INFERNAL_AXE_UNCHARGED, ItemID.INFERNAL_AXE_UNCHARGED_25371), ITEM_INFERNAL_HARPOON_OR(ItemID.INFERNAL_HARPOON, ItemID.INFERNAL_HARPOON_OR), ITEM_INFERNAL_HARPOON_OR_UNCHARGED(ItemID.INFERNAL_HARPOON_UNCHARGED, ItemID.INFERNAL_HARPOON_UNCHARGED_25367), ITEM_TRAILBLAZER_TOOL_ORNAMENT_KIT(ItemID.TRAILBLAZER_TOOL_ORNAMENT_KIT, ItemID.DRAGON_PICKAXE_OR_25376,
            ItemID.DRAGON_AXE_OR, ItemID.DRAGON_HARPOON_OR, ItemID.INFERNAL_PICKAXE_OR, ItemID.INFERNAL_AXE_OR, ItemID.INFERNAL_HARPOON_OR,
            ItemID.INFERNAL_PICKAXE_UNCHARGED_25369, ItemID.INFERNAL_AXE_UNCHARGED_25371,
            ItemID.INFERNAL_HARPOON_UNCHARGED_25367),
    ITEM_DRAGON_KITESHIELD(ItemID.DRAGON_KITESHIELD, ItemID.DRAGON_KITESHIELD_G), ITEM_DRAGON_KITESHIELD_ORNAMENT_KIT(ItemID.DRAGON_KITESHIELD_ORNAMENT_KIT, ItemID.DRAGON_KITESHIELD_G), ITEM_DRAGON_FULL_HELM(ItemID.DRAGON_FULL_HELM, ItemID.DRAGON_FULL_HELM_G), ITEM_DRAGON_FULL_HELM_ORNAMENT_KIT(ItemID.DRAGON_FULL_HELM_ORNAMENT_KIT, ItemID.DRAGON_FULL_HELM_G), ITEM_DRAGON_CHAINBODY(ItemID.DRAGON_CHAINBODY_3140, ItemID.DRAGON_CHAINBODY_G), ITEM_DRAGON_CHAINBODY_ORNAMENT_KIT(ItemID.DRAGON_CHAINBODY_ORNAMENT_KIT, ItemID.DRAGON_CHAINBODY_G), ITEM_DRAGON_PLATEBODY(ItemID.DRAGON_PLATEBODY, ItemID.DRAGON_PLATEBODY_G), ITEM_DRAGON_PLATEBODY_ORNAMENT_KIT(ItemID.DRAGON_PLATEBODY_ORNAMENT_KIT, ItemID.DRAGON_PLATEBODY_G), ITEM_DRAGON_PLATESKIRT(ItemID.DRAGON_PLATESKIRT, ItemID.DRAGON_PLATESKIRT_G), ITEM_DRAGON_SKIRT_ORNAMENT_KIT(ItemID.DRAGON_LEGSSKIRT_ORNAMENT_KIT, ItemID.DRAGON_PLATESKIRT_G), ITEM_DRAGON_PLATELEGS(ItemID.DRAGON_PLATELEGS, ItemID.DRAGON_PLATELEGS_G), ITEM_DRAGON_LEGS_ORNAMENT_KIT(ItemID.DRAGON_LEGSSKIRT_ORNAMENT_KIT, ItemID.DRAGON_PLATELEGS_G), ITEM_DRAGON_SQ_SHIELD(ItemID.DRAGON_SQ_SHIELD, ItemID.DRAGON_SQ_SHIELD_G), ITEM_DRAGON_SQ_SHIELD_ORNAMENT_KIT(ItemID.DRAGON_SQ_SHIELD_ORNAMENT_KIT, ItemID.DRAGON_SQ_SHIELD_G), ITEM_DRAGON_BOOTS(ItemID.DRAGON_BOOTS, ItemID.DRAGON_BOOTS_G), ITEM_DRAGON_BOOTS_ORNAMENT_KIT(ItemID.DRAGON_BOOTS_ORNAMENT_KIT, ItemID.DRAGON_BOOTS_G),  // Rune ornament kits
    ITEM_RUNE_SCIMITAR_GUTHIX(ItemID.RUNE_SCIMITAR, ItemID.RUNE_SCIMITAR_23330), ITEM_RUNE_SCIMITAR_ORNAMENT_KIT_GUTHIX(ItemID.RUNE_SCIMITAR_ORNAMENT_KIT_GUTHIX, ItemID.RUNE_SCIMITAR_23330), ITEM_RUNE_SCIMITAR_SARADOMIN(ItemID.RUNE_SCIMITAR, ItemID.RUNE_SCIMITAR_23332), ITEM_RUNE_SCIMITAR_ORNAMENT_KIT_SARADOMIN(ItemID.RUNE_SCIMITAR_ORNAMENT_KIT_SARADOMIN,
            ItemID.RUNE_SCIMITAR_23332),
    ITEM_RUNE_SCIMITAR_ZAMORAK(ItemID.RUNE_SCIMITAR, ItemID.RUNE_SCIMITAR_23334), ITEM_RUNE_SCIMITAR_ORNAMENT_KIT_ZAMORAK(ItemID.RUNE_SCIMITAR_ORNAMENT_KIT_ZAMORAK, ItemID.RUNE_SCIMITAR_23334), ITEM_RUNE_DEFENDER(ItemID.RUNE_DEFENDER, ItemID.RUNE_DEFENDER_T), ITEM_RUNE_DEFENDER_ORNAMENT_KIT(ItemID.RUNE_DEFENDER_ORNAMENT_KIT, ItemID.RUNE_DEFENDER_T),  // Godsword ornament kits
    ITEM_ARMADYL_GODSWORD(ItemID.ARMADYL_GODSWORD, ItemID.ARMADYL_GODSWORD_OR), ITEM_ARMADYL_GODSWORD_ORNAMENT_KIT(ItemID.ARMADYL_GODSWORD_ORNAMENT_KIT, ItemID.ARMADYL_GODSWORD_OR), ITEM_BANDOS_GODSWORD(ItemID.BANDOS_GODSWORD, ItemID.BANDOS_GODSWORD_OR), ITEM_BANDOS_GODSWORD_ORNAMENT_KIT(ItemID.BANDOS_GODSWORD_ORNAMENT_KIT, ItemID.BANDOS_GODSWORD_OR), ITEM_ZAMORAK_GODSWORD(ItemID.ZAMORAK_GODSWORD, ItemID.ZAMORAK_GODSWORD_OR), ITEM_ZAMORAK_GODSWORD_ORNAMENT_KIT(ItemID.ZAMORAK_GODSWORD_ORNAMENT_KIT, ItemID.ZAMORAK_GODSWORD_OR), ITEM_SARADOMIN_GODSWORD(ItemID.SARADOMIN_GODSWORD, ItemID.SARADOMIN_GODSWORD_OR), ITEM_SARADOMIN_GODSWORD_ORNAMENT_KIT(ItemID.SARADOMIN_GODSWORD_ORNAMENT_KIT, ItemID.SARADOMIN_GODSWORD_OR),  // Jewellery ornament kits
    ITEM_AMULET_OF_TORTURE(ItemID.AMULET_OF_TORTURE, ItemID.AMULET_OF_TORTURE_OR), ITEM_TORTURE_ORNAMENT_KIT(ItemID.TORTURE_ORNAMENT_KIT, ItemID.AMULET_OF_TORTURE_OR), ITEM_NECKLACE_OF_ANGUISH(ItemID.NECKLACE_OF_ANGUISH, ItemID.NECKLACE_OF_ANGUISH_OR), ITEM_ANGUISH_ORNAMENT_KIT(ItemID.ANGUISH_ORNAMENT_KIT, ItemID.NECKLACE_OF_ANGUISH_OR), ITEM_OCCULT_NECKLACE(ItemID.OCCULT_NECKLACE, ItemID.OCCULT_NECKLACE_OR), ITEM_OCCULT_ORNAMENT_KIT(ItemID.OCCULT_ORNAMENT_KIT, ItemID.OCCULT_NECKLACE_OR), ITEM_AMULET_OF_FURY(ItemID.AMULET_OF_FURY, ItemID.AMULET_OF_FURY_OR, ItemID.AMULET_OF_BLOOD_FURY), ITEM_FURY_ORNAMENT_KIT(ItemID.FURY_ORNAMENT_KIT, ItemID.AMULET_OF_FURY_OR), ITEM_TORMENTED_BRACELET(ItemID.TORMENTED_BRACELET, ItemID.TORMENTED_BRACELET_OR), ITEM_TORMENTED_ORNAMENT_KIT(ItemID.TORMENTED_ORNAMENT_KIT, ItemID.TORMENTED_BRACELET_OR), ITEM_BERSERKER_NECKLACE(ItemID.BERSERKER_NECKLACE, ItemID.BERSERKER_NECKLACE_OR), ITEM_BERSERKER_NECKLACE_ORNAMENT_KIT(ItemID.BERSERKER_NECKLACE_ORNAMENT_KIT, ItemID.BERSERKER_NECKLACE_OR),  // Ensouled heads
    ITEM_ENSOULED_GOBLIN_HEAD(ItemID.ENSOULED_GOBLIN_HEAD_13448, ItemID.ENSOULED_GOBLIN_HEAD), ITEM_ENSOULED_MONKEY_HEAD(ItemID.ENSOULED_MONKEY_HEAD_13451, ItemID.ENSOULED_MONKEY_HEAD), ITEM_ENSOULED_IMP_HEAD(ItemID.ENSOULED_IMP_HEAD_13454, ItemID.ENSOULED_IMP_HEAD), ITEM_ENSOULED_MINOTAUR_HEAD(ItemID.ENSOULED_MINOTAUR_HEAD_13457, ItemID.ENSOULED_MINOTAUR_HEAD), ITEM_ENSOULED_SCORPION_HEAD(ItemID.ENSOULED_SCORPION_HEAD_13460, ItemID.ENSOULED_SCORPION_HEAD), ITEM_ENSOULED_BEAR_HEAD(ItemID.ENSOULED_BEAR_HEAD_13463, ItemID.ENSOULED_BEAR_HEAD), ITEM_ENSOULED_UNICORN_HEAD(ItemID.ENSOULED_UNICORN_HEAD_13466, ItemID.ENSOULED_UNICORN_HEAD), ITEM_ENSOULED_DOG_HEAD(ItemID.ENSOULED_DOG_HEAD_13469, ItemID.ENSOULED_DOG_HEAD), ITEM_ENSOULED_CHAOS_DRUID_HEAD(ItemID.ENSOULED_CHAOS_DRUID_HEAD_13472, ItemID.ENSOULED_CHAOS_DRUID_HEAD), ITEM_ENSOULED_GIANT_HEAD(ItemID.ENSOULED_GIANT_HEAD_13475, ItemID.ENSOULED_GIANT_HEAD), ITEM_ENSOULED_OGRE_HEAD(ItemID.ENSOULED_OGRE_HEAD_13478, ItemID.ENSOULED_OGRE_HEAD), ITEM_ENSOULED_ELF_HEAD(ItemID.ENSOULED_ELF_HEAD_13481, ItemID.ENSOULED_ELF_HEAD), ITEM_ENSOULED_TROLL_HEAD(ItemID.ENSOULED_TROLL_HEAD_13484, ItemID.ENSOULED_TROLL_HEAD), ITEM_ENSOULED_HORROR_HEAD(ItemID.ENSOULED_HORROR_HEAD_13487, ItemID.ENSOULED_HORROR_HEAD), ITEM_ENSOULED_KALPHITE_HEAD(ItemID.ENSOULED_KALPHITE_HEAD_13490, ItemID.ENSOULED_KALPHITE_HEAD), ITEM_ENSOULED_DAGANNOTH_HEAD(ItemID.ENSOULED_DAGANNOTH_HEAD_13493, ItemID.ENSOULED_DAGANNOTH_HEAD), ITEM_ENSOULED_BLOODVELD_HEAD(ItemID.ENSOULED_BLOODVELD_HEAD_13496, ItemID.ENSOULED_BLOODVELD_HEAD), ITEM_ENSOULED_TZHAAR_HEAD(ItemID.ENSOULED_TZHAAR_HEAD_13499, ItemID.ENSOULED_TZHAAR_HEAD), ITEM_ENSOULED_DEMON_HEAD(ItemID.ENSOULED_DEMON_HEAD_13502, ItemID.ENSOULED_DEMON_HEAD), ITEM_ENSOULED_AVIANSIE_HEAD(ItemID.ENSOULED_AVIANSIE_HEAD_13505, ItemID.ENSOULED_AVIANSIE_HEAD), ITEM_ENSOULED_ABYSSAL_HEAD(ItemID.ENSOULED_ABYSSAL_HEAD_13508, ItemID.ENSOULED_ABYSSAL_HEAD), ITEM_ENSOULED_DRAGON_HEAD(ItemID.ENSOULED_DRAGON_HEAD_13511, ItemID.ENSOULED_DRAGON_HEAD),  // Imbued rings
    ITEM_BERSERKER_RING(ItemID.BERSERKER_RING, ItemID.BERSERKER_RING_I, ItemID.BERSERKER_RING_I_25264), ITEM_SEERS_RING(ItemID.SEERS_RING, ItemID.SEERS_RING_I, ItemID.SEERS_RING_I_25258), ITEM_WARRIOR_RING(ItemID.WARRIOR_RING, ItemID.WARRIOR_RING_I, ItemID.WARRIOR_RING_I_25262), ITEM_ARCHERS_RING(ItemID.ARCHERS_RING, ItemID.ARCHERS_RING_I, ItemID.ARCHERS_RING_I_25260), ITEM_TREASONOUS_RING(ItemID.TREASONOUS_RING, ItemID.TREASONOUS_RING_I, ItemID.TREASONOUS_RING_I_25256), ITEM_TYRANNICAL_RING(ItemID.TYRANNICAL_RING, ItemID.TYRANNICAL_RING_I, ItemID.TYRANNICAL_RING_I_25254), ITEM_RING_OF_THE_GODS(ItemID.RING_OF_THE_GODS, ItemID.RING_OF_THE_GODS_I, ItemID.RING_OF_THE_GODS_I_25252), ITEM_RING_OF_SUFFERING(ItemID.RING_OF_SUFFERING, ItemID.RING_OF_SUFFERING_I, ItemID.RING_OF_SUFFERING_R,
            ItemID.RING_OF_SUFFERING_RI, ItemID.RING_OF_SUFFERING_I_25246, ItemID.RING_OF_SUFFERING_RI_25248),
    ITEM_GRANITE_RING(ItemID.GRANITE_RING, ItemID.GRANITE_RING_I, ItemID.GRANITE_RING_I_25193),  // Bounty hunter
    ITEM_GRANITE_MAUL(ItemID.GRANITE_MAUL, ItemID.GRANITE_MAUL_12848), ITEM_MAGIC_SHORTBOW(ItemID.MAGIC_SHORTBOW, ItemID.MAGIC_SHORTBOW_I), ITEM_MAGIC_SHORTBOW_SCROLL(ItemID.MAGIC_SHORTBOW_SCROLL, ItemID.MAGIC_SHORTBOW_I), ITEM_SARADOMINS_BLESSED_SWORD(ItemID.SARADOMINS_TEAR, ItemID.SARADOMINS_BLESSED_SWORD),  // Jewellery with charges
    ITEM_RING_OF_WEALTH(ItemID.RING_OF_WEALTH, ItemID.RING_OF_WEALTH_I, ItemID.RING_OF_WEALTH_1, ItemID.RING_OF_WEALTH_I1,
            ItemID.RING_OF_WEALTH_2, ItemID.RING_OF_WEALTH_I2, ItemID.RING_OF_WEALTH_3, ItemID.RING_OF_WEALTH_I3, ItemID.RING_OF_WEALTH_4,
            ItemID.RING_OF_WEALTH_I4, ItemID.RING_OF_WEALTH_I5),
    ITEM_RING_OF_WEALTH_SCROLL(ItemID.RING_OF_WEALTH_SCROLL, ItemID.RING_OF_WEALTH_I, ItemID.RING_OF_WEALTH_I1,
            ItemID.RING_OF_WEALTH_I2, ItemID.RING_OF_WEALTH_I3, ItemID.RING_OF_WEALTH_I4, ItemID.RING_OF_WEALTH_I5),
    ITEM_AMULET_OF_GLORY(ItemID.AMULET_OF_GLORY, ItemID.AMULET_OF_GLORY1, ItemID.AMULET_OF_GLORY2, ItemID.AMULET_OF_GLORY3,
            ItemID.AMULET_OF_GLORY5),
    ITEM_AMULET_OF_GLORY_T(ItemID.AMULET_OF_GLORY_T, ItemID.AMULET_OF_GLORY_T1, ItemID.AMULET_OF_GLORY_T2,
            ItemID.AMULET_OF_GLORY_T3, ItemID.AMULET_OF_GLORY_T5),
    ITEM_SKILLS_NECKLACE(ItemID.SKILLS_NECKLACE, ItemID.SKILLS_NECKLACE1, ItemID.SKILLS_NECKLACE2, ItemID.SKILLS_NECKLACE3,
            ItemID.SKILLS_NECKLACE5),
    ITEM_RING_OF_DUELING(ItemID.RING_OF_DUELING8, ItemID.RING_OF_DUELING1, ItemID.RING_OF_DUELING2, ItemID.RING_OF_DUELING3,
            ItemID.RING_OF_DUELING4, ItemID.RING_OF_DUELING5, ItemID.RING_OF_DUELING6, ItemID.RING_OF_DUELING7),
    ITEM_GAMES_NECKLACE(ItemID.GAMES_NECKLACE8, ItemID.GAMES_NECKLACE1, ItemID.GAMES_NECKLACE2, ItemID.GAMES_NECKLACE3,
            ItemID.GAMES_NECKLACE4, ItemID.GAMES_NECKLACE5, ItemID.GAMES_NECKLACE6, ItemID.GAMES_NECKLACE7),  // Degradable/charged weaponry/armour
    ITEM_ABYSSAL_WHIP(ItemID.ABYSSAL_WHIP, ItemID.VOLCANIC_ABYSSAL_WHIP, ItemID.FROZEN_ABYSSAL_WHIP), ITEM_KRAKEN_TENTACLE(ItemID.KRAKEN_TENTACLE, ItemID.ABYSSAL_TENTACLE), ITEM_TRIDENT_OF_THE_SEAS(ItemID.UNCHARGED_TRIDENT, ItemID.TRIDENT_OF_THE_SEAS), ITEM_TRIDENT_OF_THE_SEAS_E(ItemID.UNCHARGED_TRIDENT_E, ItemID.TRIDENT_OF_THE_SEAS_E), ITEM_TRIDENT_OF_THE_SWAMP(ItemID.UNCHARGED_TOXIC_TRIDENT, ItemID.TRIDENT_OF_THE_SWAMP), ITEM_TRIDENT_OF_THE_SWAMP_E(ItemID.UNCHARGED_TOXIC_TRIDENT_E, ItemID.TRIDENT_OF_THE_SWAMP_E), ITEM_TOXIC_BLOWPIPE(ItemID.TOXIC_BLOWPIPE_EMPTY, ItemID.TOXIC_BLOWPIPE), ITEM_TOXIC_STAFF_OFF_THE_DEAD(ItemID.TOXIC_STAFF_UNCHARGED, ItemID.TOXIC_STAFF_OF_THE_DEAD), ITEM_SERPENTINE_HELM(ItemID.SERPENTINE_HELM_UNCHARGED, ItemID.SERPENTINE_HELM, ItemID.TANZANITE_HELM_UNCHARGED,
            ItemID.TANZANITE_HELM, ItemID.MAGMA_HELM_UNCHARGED, ItemID.MAGMA_HELM),
    ITEM_DRAGONFIRE_SHIELD(ItemID.DRAGONFIRE_SHIELD_11284, ItemID.DRAGONFIRE_SHIELD), ITEM_DRAGONFIRE_WARD(ItemID.DRAGONFIRE_WARD_22003, ItemID.DRAGONFIRE_WARD), ITEM_ANCIENT_WYVERN_SHIELD(ItemID.ANCIENT_WYVERN_SHIELD_21634, ItemID.ANCIENT_WYVERN_SHIELD), ITEM_SANGUINESTI_STAFF(ItemID.SANGUINESTI_STAFF_UNCHARGED, ItemID.SANGUINESTI_STAFF,
            ItemID.HOLY_SANGUINESTI_STAFF_UNCHARGED, ItemID.HOLY_SANGUINESTI_STAFF),
    ITEM_SCYTHE_OF_VITUR(ItemID.SCYTHE_OF_VITUR_UNCHARGED, ItemID.SCYTHE_OF_VITUR, ItemID.HOLY_SCYTHE_OF_VITUR_UNCHARGED,
            ItemID.HOLY_SCYTHE_OF_VITUR, ItemID.SANGUINE_SCYTHE_OF_VITUR_UNCHARGED, ItemID.SANGUINE_SCYTHE_OF_VITUR),
    ITEM_TOME_OF_FIRE(ItemID.TOME_OF_FIRE_EMPTY, ItemID.TOME_OF_FIRE), ITEM_CRAWS_BOW(ItemID.CRAWS_BOW_U, ItemID.CRAWS_BOW), ITEM_VIGGORAS_CHAINMACE(ItemID.VIGGORAS_CHAINMACE_U, ItemID.VIGGORAS_CHAINMACE), ITEM_THAMMARONS_SCEPTRE(ItemID.THAMMARONS_SCEPTRE_U, ItemID.THAMMARONS_SCEPTRE), ITEM_BRYOPHYTAS_STAFF(ItemID.BRYOPHYTAS_STAFF_UNCHARGED, ItemID.BRYOPHYTAS_STAFF), ITEM_RING_OF_ENDURANCE(ItemID.RING_OF_ENDURANCE_UNCHARGED_24844, ItemID.RING_OF_ENDURANCE),  // Infinity colour kits
    ITEM_INFINITY_TOP(ItemID.INFINITY_TOP, ItemID.INFINITY_TOP_20574, ItemID.DARK_INFINITY_TOP, ItemID.LIGHT_INFINITY_TOP), ITEM_INFINITY_TOP_LIGHT_COLOUR_KIT(ItemID.LIGHT_INFINITY_COLOUR_KIT, ItemID.LIGHT_INFINITY_TOP), ITEM_INFINITY_TOP_DARK_COLOUR_KIT(ItemID.DARK_INFINITY_COLOUR_KIT, ItemID.DARK_INFINITY_TOP), ITEM_INFINITY_BOTTOMS(ItemID.INFINITY_BOTTOMS, ItemID.INFINITY_BOTTOMS_20575, ItemID.DARK_INFINITY_BOTTOMS,
            ItemID.LIGHT_INFINITY_BOTTOMS),
    ITEM_INFINITY_BOTTOMS_LIGHT_COLOUR_KIT(ItemID.LIGHT_INFINITY_COLOUR_KIT, ItemID.LIGHT_INFINITY_BOTTOMS), ITEM_INFINITY_BOTTOMS_DARK_COLOUR_KIT(ItemID.DARK_INFINITY_COLOUR_KIT, ItemID.DARK_INFINITY_BOTTOMS), ITEM_INFINITY_HAT(ItemID.INFINITY_HAT, ItemID.DARK_INFINITY_HAT, ItemID.LIGHT_INFINITY_HAT), ITEM_INFINITY_HAT_LIGHT_COLOUR_KIT(ItemID.LIGHT_INFINITY_COLOUR_KIT, ItemID.LIGHT_INFINITY_HAT), ITEM_INFINITY_HAT_DARK_COLOUR_KIT(ItemID.DARK_INFINITY_COLOUR_KIT, ItemID.DARK_INFINITY_HAT),  // Miscellaneous ornament kits
    ITEM_DARK_BOW(ItemID.DARK_BOW, ItemID.DARK_BOW_12765, ItemID.DARK_BOW_12766, ItemID.DARK_BOW_12767, ItemID.DARK_BOW_12768,
            ItemID.DARK_BOW_20408),
    ITEM_ODIUM_WARD(ItemID.ODIUM_WARD, ItemID.ODIUM_WARD_12807), ITEM_MALEDICTION_WARD(ItemID.MALEDICTION_WARD, ItemID.MALEDICTION_WARD_12806), ITEM_STEAM_BATTLESTAFF(ItemID.STEAM_BATTLESTAFF, ItemID.STEAM_BATTLESTAFF_12795), ITEM_LAVA_BATTLESTAFF(ItemID.LAVA_BATTLESTAFF, ItemID.LAVA_BATTLESTAFF_21198), ITEM_TZHAARKETOM(ItemID.TZHAARKETOM, ItemID.TZHAARKETOM_T), ITEM_TZHAARKETOM_ORNAMENT_KIT(ItemID.TZHAARKETOM_ORNAMENT_KIT, ItemID.TZHAARKETOM_T),  // Slayer helm/black mask
    ITEM_BLACK_MASK(
            ItemID.BLACK_MASK, ItemID.BLACK_MASK_I, ItemID.BLACK_MASK_1, ItemID.BLACK_MASK_1_I, ItemID.BLACK_MASK_2, ItemID.BLACK_MASK_2_I,
            ItemID.BLACK_MASK_3, ItemID.BLACK_MASK_3_I, ItemID.BLACK_MASK_4, ItemID.BLACK_MASK_4_I, ItemID.BLACK_MASK_5,
            ItemID.BLACK_MASK_5_I, ItemID.BLACK_MASK_6, ItemID.BLACK_MASK_6_I, ItemID.BLACK_MASK_7, ItemID.BLACK_MASK_7_I, ItemID.BLACK_MASK_8,
            ItemID.BLACK_MASK_8_I, ItemID.BLACK_MASK_9, ItemID.BLACK_MASK_9_I, ItemID.BLACK_MASK_10_I,
            ItemID.SLAYER_HELMET, ItemID.SLAYER_HELMET_I, ItemID.BLACK_SLAYER_HELMET, ItemID.BLACK_SLAYER_HELMET_I,
            ItemID.PURPLE_SLAYER_HELMET, ItemID.PURPLE_SLAYER_HELMET_I, ItemID.RED_SLAYER_HELMET, ItemID.RED_SLAYER_HELMET_I,
            ItemID.GREEN_SLAYER_HELMET, ItemID.GREEN_SLAYER_HELMET_I, ItemID.TURQUOISE_SLAYER_HELMET,
            ItemID.TURQUOISE_SLAYER_HELMET_I, ItemID.TWISTED_SLAYER_HELMET, ItemID.TWISTED_SLAYER_HELMET_I,
            ItemID.HYDRA_SLAYER_HELMET, ItemID.HYDRA_SLAYER_HELMET_I,
            ItemID.SLAYER_HELMET_I_25177, ItemID.BLACK_SLAYER_HELMET_I_25179, ItemID.GREEN_SLAYER_HELMET_I_25181,
            ItemID.RED_SLAYER_HELMET_I_25183, ItemID.PURPLE_SLAYER_HELMET_I_25185, ItemID.TURQUOISE_SLAYER_HELMET_I_25187,
            ItemID.HYDRA_SLAYER_HELMET_I_25189, ItemID.TWISTED_SLAYER_HELMET_I_25191,
            ItemID.BLACK_MASK_I_25276, ItemID.BLACK_MASK_1_I_25275, ItemID.BLACK_MASK_2_I_25274, ItemID.BLACK_MASK_3_I_25273,
            ItemID.BLACK_MASK_4_I_25272, ItemID.BLACK_MASK_5_I_25271, ItemID.BLACK_MASK_6_I_25270, ItemID.BLACK_MASK_7_I_25269,
            ItemID.BLACK_MASK_8_I_25268, ItemID.BLACK_MASK_9_I_25267, ItemID.BLACK_MASK_10_I_25266),  // Pharaoh's Sceptres
    ITEM_PHARAOHS_SCEPTRE_1(ItemID.PHARAOHS_SCEPTRE, ItemID.PHARAOHS_SCEPTRE_1), ITEM_PHARAOHS_SCEPTRE_2(ItemID.PHARAOHS_SCEPTRE, ItemID.PHARAOHS_SCEPTRE_2), ITEM_PHARAOHS_SCEPTRE_4(ItemID.PHARAOHS_SCEPTRE, ItemID.PHARAOHS_SCEPTRE_4), ITEM_PHARAOHS_SCEPTRE_5(ItemID.PHARAOHS_SCEPTRE, ItemID.PHARAOHS_SCEPTRE_5), ITEM_PHARAOHS_SCEPTRE_6(ItemID.PHARAOHS_SCEPTRE, ItemID.PHARAOHS_SCEPTRE_6), ITEM_PHARAOHS_SCEPTRE_7(ItemID.PHARAOHS_SCEPTRE, ItemID.PHARAOHS_SCEPTRE_7), ITEM_PHARAOHS_SCEPTRE_8(ItemID.PHARAOHS_SCEPTRE, ItemID.PHARAOHS_SCEPTRE_8),  // Revertible items
    ITEM_HYDRA_LEATHER(ItemID.HYDRA_LEATHER, ItemID.FEROCIOUS_GLOVES), ITEM_HYDRA_TAIL(ItemID.HYDRA_TAIL, ItemID.BONECRUSHER_NECKLACE), ITEM_DRAGONBONE_NECKLACE(ItemID.DRAGONBONE_NECKLACE, ItemID.BONECRUSHER_NECKLACE), ITEM_BOTTOMLESS_COMPOST_BUCKET(ItemID.BOTTOMLESS_COMPOST_BUCKET, ItemID.BOTTOMLESS_COMPOST_BUCKET_22997), ITEM_BASILISK_JAW(ItemID.BASILISK_JAW, ItemID.NEITIZNOT_FACEGUARD), ITEM_HELM_OF_NEITIZNOT(ItemID.HELM_OF_NEITIZNOT, ItemID.NEITIZNOT_FACEGUARD), ITEM_TWISTED_HORNS(ItemID.TWISTED_HORNS, ItemID.TWISTED_SLAYER_HELMET, ItemID.TWISTED_SLAYER_HELMET_I,
            ItemID.TWISTED_SLAYER_HELMET_I_25191),
    ITEM_ELDRITCH_ORB(ItemID.ELDRITCH_ORB, ItemID.ELDRITCH_NIGHTMARE_STAFF), ITEM_HARMONISED_ORB(ItemID.HARMONISED_ORB, ItemID.HARMONISED_NIGHTMARE_STAFF), ITEM_VOLATILE_ORB(ItemID.VOLATILE_ORB, ItemID.VOLATILE_NIGHTMARE_STAFF), ITEM_NIGHTMARE_STAFF(ItemID.NIGHTMARE_STAFF, ItemID.ELDRITCH_NIGHTMARE_STAFF, ItemID.HARMONISED_NIGHTMARE_STAFF,
            ItemID.VOLATILE_NIGHTMARE_STAFF),
    ITEM_GHARZI_RAPIER(ItemID.GHRAZI_RAPIER, ItemID.HOLY_GHRAZI_RAPIER),  // Trouver Parchment
    ITEM_TROUVER_PARCHMENT(
            ItemID.TROUVER_PARCHMENT, ItemID.INFERNAL_MAX_CAPE_L, ItemID.FIRE_MAX_CAPE_L, ItemID.ASSEMBLER_MAX_CAPE_L,
            ItemID.BRONZE_DEFENDER_L, ItemID.IRON_DEFENDER_L, ItemID.STEEL_DEFENDER_L, ItemID.BLACK_DEFENDER_L, ItemID.MITHRIL_DEFENDER_L,
            ItemID.ADAMANT_DEFENDER_L,
            ItemID.RUNE_DEFENDER_L, ItemID.DRAGON_DEFENDER_L, ItemID.DECORATIVE_SWORD_L, ItemID.DECORATIVE_ARMOUR_L,
            ItemID.DECORATIVE_ARMOUR_L_24159, ItemID.DECORATIVE_HELM_L, ItemID.DECORATIVE_SHIELD_L, ItemID.DECORATIVE_ARMOUR_L_24162,
            ItemID.DECORATIVE_ARMOUR_L_24163, ItemID.DECORATIVE_ARMOUR_L_24164,
            ItemID.DECORATIVE_ARMOUR_L_24165, ItemID.DECORATIVE_ARMOUR_L_24166, ItemID.DECORATIVE_ARMOUR_L_24167,
            ItemID.DECORATIVE_ARMOUR_L_24168, ItemID.SARADOMIN_HALO_L, ItemID.ZAMORAK_HALO_L, ItemID.GUTHIX_HALO_L, ItemID.HEALER_HAT_L,
            ItemID.FIGHTER_HAT_L, ItemID.RANGER_HAT_L,
            ItemID.FIGHTER_TORSO_L, ItemID.PENANCE_SKIRT_L, ItemID.VOID_KNIGHT_TOP_L, ItemID.ELITE_VOID_TOP_L, ItemID.VOID_KNIGHT_ROBE_L,
            ItemID.ELITE_VOID_ROBE_L, ItemID.VOID_KNIGHT_MACE_L, ItemID.VOID_KNIGHT_GLOVES_L, ItemID.VOID_MAGE_HELM_L,
            ItemID.VOID_RANGER_HELM_L,
            ItemID.VOID_MELEE_HELM_L, ItemID.AVERNIC_DEFENDER_L, ItemID.ARMADYL_HALO_L, ItemID.BANDOS_HALO_L, ItemID.SEREN_HALO_L,
            ItemID.ANCIENT_HALO_L, ItemID.BRASSICA_HALO_L, ItemID.AVAS_ASSEMBLER_L, ItemID.FIRE_CAPE_L, ItemID.INFERNAL_CAPE_L,
            ItemID.IMBUED_SARADOMIN_MAX_CAPE_L,
            ItemID.IMBUED_ZAMORAK_MAX_CAPE_L, ItemID.IMBUED_GUTHIX_MAX_CAPE_L, ItemID.IMBUED_SARADOMIN_CAPE_L,
            ItemID.IMBUED_ZAMORAK_CAPE_L, ItemID.IMBUED_GUTHIX_CAPE_L, ItemID.RUNE_POUCH_L, ItemID.RUNNER_HAT_L, ItemID.DECORATIVE_BOOTS_L,
            ItemID.DECORATIVE_FULL_HELM_L),
    ITEM_TROUVER_PARCHMENT_REFUND_LARGE(
            ItemID.COINS_995, 475000L, ItemID.INFERNAL_MAX_CAPE_L, ItemID.FIRE_MAX_CAPE_L, ItemID.ASSEMBLER_MAX_CAPE_L,
            ItemID.RUNE_DEFENDER_L, ItemID.DRAGON_DEFENDER_L, ItemID.DECORATIVE_SWORD_L, ItemID.DECORATIVE_ARMOUR_L,
            ItemID.DECORATIVE_ARMOUR_L_24159, ItemID.DECORATIVE_HELM_L, ItemID.DECORATIVE_SHIELD_L,
            ItemID.DECORATIVE_ARMOUR_L_24162, ItemID.DECORATIVE_ARMOUR_L_24163, ItemID.DECORATIVE_ARMOUR_L_24164,
            ItemID.DECORATIVE_ARMOUR_L_24165, ItemID.DECORATIVE_ARMOUR_L_24166, ItemID.DECORATIVE_ARMOUR_L_24167,
            ItemID.DECORATIVE_ARMOUR_L_24168, ItemID.SARADOMIN_HALO_L,
            ItemID.ZAMORAK_HALO_L, ItemID.GUTHIX_HALO_L, ItemID.HEALER_HAT_L, ItemID.FIGHTER_HAT_L, ItemID.RANGER_HAT_L, ItemID.FIGHTER_TORSO_L,
            ItemID.PENANCE_SKIRT_L, ItemID.VOID_KNIGHT_TOP_L, ItemID.ELITE_VOID_TOP_L, ItemID.VOID_KNIGHT_ROBE_L, ItemID.ELITE_VOID_ROBE_L,
            ItemID.VOID_KNIGHT_MACE_L,
            ItemID.VOID_KNIGHT_GLOVES_L, ItemID.VOID_MAGE_HELM_L, ItemID.VOID_RANGER_HELM_L, ItemID.VOID_MELEE_HELM_L,
            ItemID.AVERNIC_DEFENDER_L, ItemID.ARMADYL_HALO_L, ItemID.BANDOS_HALO_L, ItemID.SEREN_HALO_L, ItemID.ANCIENT_HALO_L,
            ItemID.BRASSICA_HALO_L, ItemID.AVAS_ASSEMBLER_L,
            ItemID.FIRE_CAPE_L, ItemID.INFERNAL_CAPE_L, ItemID.IMBUED_SARADOMIN_MAX_CAPE_L, ItemID.IMBUED_ZAMORAK_MAX_CAPE_L,
            ItemID.IMBUED_GUTHIX_MAX_CAPE_L, ItemID.IMBUED_SARADOMIN_CAPE_L, ItemID.IMBUED_ZAMORAK_CAPE_L,
            ItemID.IMBUED_GUTHIX_CAPE_L, ItemID.RUNE_POUCH_L, ItemID.RUNNER_HAT_L, ItemID.DECORATIVE_BOOTS_L, ItemID.DECORATIVE_FULL_HELM_L),
    ITEM_TROUVER_PARCHMENT_REFUND_SMALL(ItemID.COINS_995, 47500L, ItemID.BRONZE_DEFENDER_L, ItemID.IRON_DEFENDER_L,
            ItemID.STEEL_DEFENDER_L, ItemID.BLACK_DEFENDER_L, ItemID.MITHRIL_DEFENDER_L, ItemID.ADAMANT_DEFENDER_L),  // Crystal items
    ITEM_CRYSTAL_TOOL_SEED(ItemID.CRYSTAL_TOOL_SEED, ItemID.CRYSTAL_AXE, ItemID.CRYSTAL_AXE_INACTIVE, ItemID.CRYSTAL_HARPOON,
            ItemID.CRYSTAL_HARPOON_INACTIVE, ItemID.CRYSTAL_PICKAXE, ItemID.CRYSTAL_PICKAXE_INACTIVE),
    ITEM_CRYSTAL_AXE(ItemID.DRAGON_AXE, ItemID.CRYSTAL_AXE, ItemID.CRYSTAL_AXE_INACTIVE), ITEM_CRYSTAL_HARPOON(ItemID.DRAGON_HARPOON, ItemID.CRYSTAL_HARPOON, ItemID.CRYSTAL_HARPOON_INACTIVE), ITEM_CRYSTAL_PICKAXE(ItemID.DRAGON_PICKAXE, ItemID.CRYSTAL_PICKAXE, ItemID.CRYSTAL_PICKAXE_INACTIVE), ITEM_BLADE_OF_SAELDOR(ItemID.BLADE_OF_SAELDOR_INACTIVE, ItemID.BLADE_OF_SAELDOR, ItemID.BLADE_OF_SAELDOR_C), ITEM_CRYSTAL_BOW(ItemID.CRYSTAL_WEAPON_SEED, ItemID.CRYSTAL_BOW, ItemID.CRYSTAL_BOW_24123, ItemID.CRYSTAL_BOW_INACTIVE), ITEM_CRYSTAL_HALBERD(ItemID.CRYSTAL_WEAPON_SEED, ItemID.CRYSTAL_HALBERD, ItemID.CRYSTAL_HALBERD_24125,
            ItemID.CRYSTAL_HALBERD_INACTIVE),
    ITEM_CRYSTAL_SHIELD(ItemID.CRYSTAL_WEAPON_SEED, ItemID.CRYSTAL_SHIELD, ItemID.CRYSTAL_SHIELD_24127,
            ItemID.CRYSTAL_SHIELD_INACTIVE),
    ITEM_CRYSTAL_HELMET(ItemID.CRYSTAL_ARMOUR_SEED, ItemID.CRYSTAL_HELM, ItemID.CRYSTAL_HELM_INACTIVE), ITEM_CRYSTAL_LEGS(ItemID.CRYSTAL_ARMOUR_SEED, 2L, ItemID.CRYSTAL_LEGS, ItemID.CRYSTAL_LEGS_INACTIVE), ITEM_CRYSTAL_BODY(ItemID.CRYSTAL_ARMOUR_SEED, 3L, ItemID.CRYSTAL_BODY, ItemID.CRYSTAL_BODY_INACTIVE),  // Bird nests
    ITEM_BIRD_NEST(ItemID.BIRD_NEST_5075, ItemID.BIRD_NEST, ItemID.BIRD_NEST_5071, ItemID.BIRD_NEST_5072, ItemID.BIRD_NEST_5073,
            ItemID.BIRD_NEST_5074, ItemID.BIRD_NEST_7413, ItemID.BIRD_NEST_13653, ItemID.BIRD_NEST_22798, ItemID.BIRD_NEST_22800,
            ItemID.CLUE_NEST_EASY, ItemID.CLUE_NEST_MEDIUM, ItemID.CLUE_NEST_HARD, ItemID.CLUE_NEST_ELITE),  // Ancestral robes
    ITEM_ANCESTRAL_HAT(ItemID.ANCESTRAL_HAT, ItemID.TWISTED_ANCESTRAL_HAT), ITEM_ANCESTRAL_ROBE_TOP(ItemID.ANCESTRAL_ROBE_TOP, ItemID.TWISTED_ANCESTRAL_ROBE_TOP), ITEM_ANCESTRAL_ROBE_BOTTOM(ItemID.ANCESTRAL_ROBE_BOTTOM, ItemID.TWISTED_ANCESTRAL_ROBE_BOTTOM),  // Graceful
    ITEM_MARK_OF_GRACE(ItemID.AMYLASE_CRYSTAL, true, 10L, ItemID.MARK_OF_GRACE), ITEM_GRACEFUL_HOOD(ItemID.MARK_OF_GRACE, true, 28L, ItemID.GRACEFUL_HOOD), ITEM_GRACEFUL_TOP(ItemID.MARK_OF_GRACE, true, 44L, ItemID.GRACEFUL_TOP), ITEM_GRACEFUL_LEGS(ItemID.MARK_OF_GRACE, true, 48L, ItemID.GRACEFUL_LEGS), ITEM_GRACEFUL_GLOVES(ItemID.MARK_OF_GRACE, true, 24L, ItemID.GRACEFUL_GLOVES), ITEM_GRACEFUL_BOOTS(ItemID.MARK_OF_GRACE, true, 32L, ItemID.GRACEFUL_BOOTS), ITEM_GRACEFUL_CAPE(ItemID.MARK_OF_GRACE, true, 32L, ItemID.GRACEFUL_CAPE),  // Trailblazer Graceful Ornament Kit
    ITEM_TRAILBLAZER_GRACEFUL_HOOD(ItemID.TRAILBLAZER_GRACEFUL_ORNAMENT_KIT, ItemID.GRACEFUL_HOOD_25069), ITEM_TRAILBLAZER_GRACEFUL_TOP(ItemID.TRAILBLAZER_GRACEFUL_ORNAMENT_KIT, ItemID.GRACEFUL_TOP_25075), ITEM_TRAILBLAZER_GRACEFUL_LEGS(ItemID.TRAILBLAZER_GRACEFUL_ORNAMENT_KIT, ItemID.GRACEFUL_LEGS_25078), ITEM_TRAILBLAZER_GRACEFUL_GLOVES(ItemID.TRAILBLAZER_GRACEFUL_ORNAMENT_KIT, ItemID.GRACEFUL_GLOVES_25081), ITEM_TRAILBLAZER_GRACEFUL_BOOTS(ItemID.TRAILBLAZER_GRACEFUL_ORNAMENT_KIT, ItemID.GRACEFUL_BOOTS_25084), ITEM_TRAILBLAZER_GRACEFUL_CAPE(ItemID.TRAILBLAZER_GRACEFUL_ORNAMENT_KIT, ItemID.GRACEFUL_CAPE_25072),  // 10 golden nuggets = 100 soft clay
    ITEM_GOLDEN_NUGGET(ItemID.SOFT_CLAY, true, 10L, ItemID.GOLDEN_NUGGET), ITEM_PROSPECTOR_HELMET(ItemID.GOLDEN_NUGGET, true, 32L, ItemID.PROSPECTOR_HELMET), ITEM_PROSPECTOR_JACKET(ItemID.GOLDEN_NUGGET, true, 48L, ItemID.PROSPECTOR_JACKET), ITEM_PROSPECTOR_LEGS(ItemID.GOLDEN_NUGGET, true, 40L, ItemID.PROSPECTOR_LEGS), ITEM_PROSPECTOR_BOOTS(ItemID.GOLDEN_NUGGET, true, 24L, ItemID.PROSPECTOR_BOOTS),  // 10 unidentified minerals = 100 soft clay
    ITEM_UNIDENTIFIED_MINERALS(ItemID.SOFT_CLAY, true, 10L, ItemID.UNIDENTIFIED_MINERALS),  // Converted to coins
    ITEM_TATTERED_PAGE(ItemID.COINS_995, true, 1000L, ItemID.TATTERED_MOON_PAGE, ItemID.TATTERED_SUN_PAGE,
            ItemID.TATTERED_TEMPLE_PAGE),
    ITEM_LONG_BONE(ItemID.COINS_995, true, 1000L, ItemID.LONG_BONE), ITEM_CURVED_BONE(ItemID.COINS_995, true, 2000L, ItemID.CURVED_BONE), ITEM_PERFECT_SHELL(ItemID.COINS_995, true, 600L, ItemID.PERFECT_SHELL), ITEM_PERFECT_SNAIL_SHELL(ItemID.COINS_995, true, 600L, ItemID.PERFECT_SNAIL_SHELL), ITEM_SNAIL_SHELL(ItemID.COINS_995, true, 600L, ItemID.SNAIL_SHELL), ITEM_TORTOISE_SHELL(ItemID.COINS_995, true, 250L, ItemID.TORTOISE_SHELL);

    constructor(tradeableItem: Int, quantity: Long, vararg untradableItems: Int) : this(tradeableItem, false, quantity, *untradableItems)
    constructor(tradeableItem: Int, vararg untradableItems: Int) : this(tradeableItem, 1L, *untradableItems)

    companion object {
        private val MAPPINGS: Multimap<Int, ItemMapping> = HashMultimap.create()

        init {
            for (item in values()) {
                for (itemId in item.untradableItems) {
                    if (item.untradeable) {
                        for (variation in ItemVariationMapping.getVariations(itemId)) {
                            MAPPINGS.put(variation, item)
                        }
                    }
                    MAPPINGS.put(itemId, item)
                }
            }
        }

        /**
         * Get collection of items that are mapped from single item id.
         *
         * @param itemId the item id
         * @return the collection
         */
        fun map(itemId: Int): Collection<ItemMapping>? {
            val mapping = MAPPINGS[itemId]
            return if (mapping.isEmpty()) {
                null
            } else mapping
        }

        fun isMapped(itemId: Int): Boolean {
            return MAPPINGS.containsValue(itemId)
        }
    }
}