package meteor.plugins.oneclickagility

enum class AgilityCourse {
    DRAYNOR_VILLAGE, AL_KHARID, VARROCK, CANIFIS, FALADOR, SEERS_VILLAGE, POLLNIVNEACH, RELLEKKA, ARDOUGNE, PRIFDDINAS, APE_ATOLL, AGILITY_PYRAMID
}