/*
 * Copyright (c) 2021, 117 <https://twitter.com/117scape>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package rs117.hd.lighting

import com.google.common.collect.ImmutableMap
import rs117.hd.HDUtils.gammaToLinear
import net.runelite.api.NpcID
import rs117.hd.RGB.rgb

internal enum class NpcLight(
    val height: Int,
    val alignment: LightManager.Alignment,
    val size: Int,
    val strength: Float,
    val color: FloatArray,
    val lightType: LightManager.LightType,
    val duration: Int,
    val range: Int,
    vararg val id: Int
) {
    HELLCAT(
        20,
        LightManager.Alignment.CENTER,
        220,
        7.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.HELLCAT,
        NpcID.HELLCAT_6668,
        NpcID.LAZY_HELLCAT,
        NpcID.OVERGROWN_HELLCAT,
        NpcID.WILY_HELLCAT,
        NpcID.LAZY_HELLCAT_6689,
        NpcID.OVERGROWN_HELLCAT_6682,
        NpcID.WILY_HELLCAT_6696,
        NpcID.HELLKITTEN
    ),
    HELLRAT(
        20,
        LightManager.Alignment.CENTER,
        220,
        7.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.HELLRAT,
        NpcID.HELLRAT_BEHEMOTH
    ),
    HELLPUPPY(
        20,
        LightManager.Alignment.CENTER,
        220,
        15f,
        rgb(255, 208, 54),
        LightManager.LightType.PULSE,
        5000,
        20,
        NpcID.HELLPUPPY,
        NpcID.HELLPUPPY_3099
    ),
    IKKLE_HYDRA_RED(
        20,
        LightManager.Alignment.CENTER,
        120,
        7.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.IKKLE_HYDRA_8494,
        NpcID.IKKLE_HYDRA_8519
    ),
    IKKLE_HYDRA_GREEN(
        20,
        LightManager.Alignment.CENTER,
        120,
        7.5f,
        rgb(195, 255, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.IKKLE_HYDRA,
        NpcID.IKKLE_HYDRA_8517
    ),
    IKKLE_HYDRA_BLUE(
        20,
        LightManager.Alignment.CENTER,
        120,
        7.5f,
        rgb(0, 140, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.IKKLE_HYDRA_8493,
        NpcID.IKKLE_HYDRA_8518
    ),
    IKKLE_HYDRA_BLACK(
        20,
        LightManager.Alignment.CENTER,
        120,
        7.5f,
        rgb(53, 222, 216),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.IKKLE_HYDRA_8495,
        NpcID.IKKLE_HYDRA_8520
    ),
    PHOENIX(
        20, LightManager.Alignment.CENTER, 320, 25.0f, rgb(255, 124, 0), LightManager.LightType.FLICKER, 0, 40,
        NpcID.PHOENIX_7368, NpcID.PHOENIX_7370
    ),
    PHOENIX_WHITE(
        20,
        LightManager.Alignment.CENTER,
        320,
        15.0f,
        rgb(255, 255, 255),
        LightManager.LightType.FLICKER,
        0,
        40,
        NpcID.PHOENIX_3079,
        NpcID.PHOENIX_3083
    ),
    PHOENIX_BLUE(
        20,
        LightManager.Alignment.CENTER,
        320,
        22.5f,
        rgb(18, 77, 255),
        LightManager.LightType.FLICKER,
        0,
        40,
        NpcID.PHOENIX_3078,
        NpcID.PHOENIX_3082
    ),
    PHOENIX_PURPLE(
        20,
        LightManager.Alignment.CENTER,
        320,
        22.5f,
        rgb(162, 0, 255),
        LightManager.LightType.FLICKER,
        0,
        40,
        NpcID.PHOENIX_3080,
        NpcID.PHOENIX_3084
    ),
    PHOENIX_GREEN(
        20,
        LightManager.Alignment.CENTER,
        320,
        20.0f,
        rgb(116, 245, 81),
        LightManager.LightType.FLICKER,
        0,
        40,
        3077,
        NpcID.PHOENIX_3081
    ),
    TZREK_ZUK(
        10,
        LightManager.Alignment.CENTER,
        100,
        12.5f,
        rgb(252, 128, 45),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.TZREKZUK,
        NpcID.TZREKZUK_8011
    ),
    MIDNIGHT(
        10,
        LightManager.Alignment.CENTER,
        100,
        12.5f,
        rgb(252, 128, 45),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.MIDNIGHT,
        NpcID.MIDNIGHT_7893
    ),
    RIFT_GUARDIAN_FIRE(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 0, 0),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN,
        NpcID.RIFT_GUARDIAN_7354
    ),
    RIFT_GUARDIAN_AIR(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 255, 255),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7338,
        NpcID.RIFT_GUARDIAN_7355
    ),
    RIFT_GUARDIAN_MIND(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 163, 59),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7339,
        NpcID.RIFT_GUARDIAN_7356
    ),
    RIFT_GUARDIAN_WATER(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(18, 172, 255),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7340,
        NpcID.RIFT_GUARDIAN_7357
    ),
    RIFT_GUARDIAN_EARTH(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(184, 124, 81),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7341,
        NpcID.RIFT_GUARDIAN_7358
    ),
    RIFT_GUARDIAN_BODY(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(37, 71, 194),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7342,
        NpcID.RIFT_GUARDIAN_7359
    ),
    RIFT_GUARDIAN_COSMIC(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 255, 0),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7343,
        NpcID.RIFT_GUARDIAN_7360
    ),
    RIFT_GUARDIAN_CHAOS(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 196, 0),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7344,
        NpcID.RIFT_GUARDIAN_7361
    ),
    RIFT_GUARDIAN_NATURE(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(0, 255, 0),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7345,
        NpcID.RIFT_GUARDIAN_7362
    ),
    RIFT_GUARDIAN_LAW(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(21, 63, 232),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7346,
        NpcID.RIFT_GUARDIAN_7363
    ),
    RIFT_GUARDIAN_DEATH(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 239, 235),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7347,
        NpcID.RIFT_GUARDIAN_7364
    ),
    RIFT_GUARDIAN_SOUL(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(115, 77, 255),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7348,
        NpcID.RIFT_GUARDIAN_7365
    ),
    RIFT_GUARDIAN_ASTRAL(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(245, 153, 255),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7349,
        NpcID.RIFT_GUARDIAN_7366
    ),
    RIFT_GUARDIAN_BLOOD(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 0, 0),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_7350,
        NpcID.RIFT_GUARDIAN_7367
    ),
    RIFT_GUARDIAN_WRATH(
        50,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(212, 58, 47),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.RIFT_GUARDIAN_8024,
        NpcID.RIFT_GUARDIAN_8028
    ),
    CHAOS_ELEMENTAL_JR(
        250,
        LightManager.Alignment.CENTER,
        150,
        20.0f,
        rgb(255, 255, 255),
        LightManager.LightType.FLICKER,
        0,
        80,
        NpcID.CHAOS_ELEMENTAL_JR,
        NpcID.CHAOS_ELEMENTAL_JR_5907
    ),
    SKOTOS(
        70,
        LightManager.Alignment.CENTER,
        150,
        17.5f,
        rgb(157, 0, 255),
        LightManager.LightType.PULSE,
        3000,
        20,
        NpcID.SKOTOS,
        NpcID.SKOTOS_7671
    ),
    VANGUARD_PET(
        20,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 153, 0),
        LightManager.LightType.PULSE,
        2100,
        10,
        NpcID.VANGUARD_8198,
        NpcID.VANGUARD_8203
    ),
    VASA_MINIRIO(
        100,
        LightManager.Alignment.CENTER,
        150,
        20.0f,
        rgb(76, 0, 255),
        LightManager.LightType.PULSE,
        2400,
        30,
        NpcID.VASA_MINIRIO,
        NpcID.VASA_MINIRIO_8204
    ),
    TEKTINY(
        10,
        LightManager.Alignment.CENTER,
        100,
        20.0f,
        rgb(255, 162, 41),
        LightManager.LightType.STATIC,
        2400,
        0,
        NpcID.TEKTINY,
        NpcID.TEKTINY_8202
    ),
    ENRAGED_TEKTINY(
        10,
        LightManager.Alignment.CENTER,
        100,
        20.0f,
        rgb(255, 95, 41),
        LightManager.LightType.STATIC,
        2400,
        0,
        NpcID.ENRAGED_TEKTINY,
        NpcID.ENRAGED_TEKTINY_9513
    ),
    SMOKE_DEVIL_PET(
        20,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 242, 0),
        LightManager.LightType.PULSE,
        3000,
        15,
        NpcID.SMOKE_DEVIL_6639,
        NpcID.SMOKE_DEVIL_6655
    ),
    YOUNGLLEF(
        40,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(0, 255, 255),
        LightManager.LightType.PULSE,
        3000,
        15,
        NpcID.YOUNGLLEF,
        NpcID.YOUNGLLEF_8737
    ),
    CORRUPTED_YOUNGLLEF(
        40,
        LightManager.Alignment.CENTER,
        100,
        17.5f,
        rgb(255, 0, 0),
        LightManager.LightType.PULSE,
        3000,
        15,
        NpcID.CORRUPTED_YOUNGLLEF,
        NpcID.CORRUPTED_YOUNGLLEF_8738
    ),
    TINY_TEMPOR(
        30,
        LightManager.Alignment.CENTER,
        200,
        15.0f,
        rgb(0, 255, 255),
        LightManager.LightType.PULSE,
        3200,
        20,
        NpcID.TINY_TEMPOR,
        NpcID.TINY_TEMPOR_10637
    ),
    PYREFIEND(
        60,
        LightManager.Alignment.CENTER,
        280,
        7.5f,
        rgb(252, 122, 3),
        LightManager.LightType.FLICKER,
        0,
        20,
        NpcID.PYREFIEND,
        NpcID.PYREFIEND_434,
        NpcID.PYREFIEND_435,
        NpcID.PYREFIEND_436,
        NpcID.PYREFIEND_3139
    ),
    GHOST(
        80,
        LightManager.Alignment.CENTER,
        200,
        7.5f,
        rgb(200, 200, 255),
        LightManager.LightType.FLICKER,
        1,
        10,
        NpcID.GHOST,
        NpcID.GHOST_,
        NpcID.GHOST_86,
        NpcID.GHOST_87,
        NpcID.GHOST_88,
        NpcID.GHOST_89,
        NpcID.GHOST_90,
        NpcID.GHOST_91,
        NpcID.GHOST_92,
        NpcID.GHOST_93,
        NpcID.GHOST_94,
        NpcID.GHOST_95,
        NpcID.GHOST_96,
        NpcID.GHOST_97,
        NpcID.GHOST_98,
        NpcID.GHOST_99,
        NpcID.GHOST_472,
        NpcID.GHOST_473,
        NpcID.GHOST_474,
        NpcID.GHOST_505,
        NpcID.GHOST_506,
        NpcID.GHOST_507,
        NpcID.GHOST_920,
        NpcID.GHOST_1786,
        NpcID.GHOST_2527,
        NpcID.GHOST_2528,
        NpcID.GHOST_2529,
        NpcID.GHOST_2530,
        NpcID.GHOST_2531,
        NpcID.GHOST_2532,
        NpcID.GHOST_2533,
        NpcID.GHOST_2534,
        NpcID.GHOST__3009,
        NpcID.GHOST_3516,
        NpcID.GHOST_3625,
        NpcID.GHOST_3975,
        NpcID.GHOST_3976,
        NpcID.GHOST_3977,
        NpcID.GHOST_3978,
        NpcID.GHOST_3979,
        NpcID.GHOST_5370,
        NpcID.GHOST_7263,
        NpcID.GHOST_7264,
        NpcID.GHOST_9194,
        NpcID.GHOST_10538,
        NpcID.ANCIENT_GHOST_10558,
        NpcID.MYSTERIOUS_GHOST_3451,
        NpcID.MYSTERIOUS_GHOST_3452,
        NpcID.MYSTERIOUS_GHOST_3453,
        NpcID.MYSTERIOUS_GHOST_3454,
        NpcID.MYSTERIOUS_GHOST_3455
    ),
    SOUL_WARS_FORGOTTEN_SOUL(
        80,
        LightManager.Alignment.CENTER,
        200,
        10.0f,
        rgb(100, 180, 240),
        LightManager.LightType.FLICKER,
        1,
        10,
        NpcID.FORGOTTEN_SOUL_10524,
        NpcID.FORGOTTEN_SOUL_10525,
        NpcID.FORGOTTEN_SOUL_10526,
        NpcID.FORGOTTEN_SOUL_10534,
        NpcID.FORGOTTEN_SOUL_10535,
        NpcID.FORGOTTEN_SOUL_10536,
        NpcID.FORGOTTEN_SOUL_10537,
        NpcID.FORGOTTEN_SOUL_10544,
        NpcID.FORGOTTEN_SOUL_10545
    ),
    PHASMATYS_GHOSTS(
        80,
        LightManager.Alignment.CENTER,
        300,
        12.5f,
        rgb(100, 255, 100),
        LightManager.LightType.FLICKER,
        0,
        10,
        NpcID.GHOST_DISCIPLE,
        NpcID.NECROVARUS,
        NpcID.GHOST_GUARD,
        NpcID.TORTURED_SOUL,
        NpcID.GHOST_VILLAGER,
        NpcID.GRAVINGAS,
        NpcID.GHOST_INNKEEPER,
        NpcID.GHOST_SHOPKEEPER,
        NpcID.DROALAK,
        NpcID.DROALAK_3494,
        NpcID.SARAH_8134,
        NpcID.GHOST_BANKER,
        NpcID.GHOST_CAPTAIN,
        NpcID.GHOST_CAPTAIN_3006,
        NpcID.GHOST_SAILOR,
        NpcID.VELORINA,
        NpcID.GHOST_FARMER,
        NpcID.GHOST_GUARD_6698
    ),
    BARROWS_BROTHERS(
        50,
        LightManager.Alignment.CENTER,
        220,
        12.5f,
        rgb(255, 150, 100),
        LightManager.LightType.PULSE,
        1,
        1,
        NpcID.AHRIM_THE_BLIGHTED,
        NpcID.KARIL_THE_TAINTED,
        NpcID.DHAROK_THE_WRETCHED,
        NpcID.TORAG_THE_CORRUPTED,
        NpcID.VERAC_THE_DEFILED,
        NpcID.GUTHAN_THE_INFESTED
    ),
    SEREN(
        280,
        LightManager.Alignment.CENTER,
        500,
        12.5f,
        rgb(0, 200, 225),
        LightManager.LightType.PULSE,
        3200,
        10,
        NpcID.SEREN,
        NpcID.MEMORY_OF_SEREN,
        NpcID.MEMORY_OF_SEREN_8777,
        NpcID.MEMORY_OF_SEREN_8778,
        NpcID.MEMORY_OF_SEREN_8779,
        NpcID.MEMORY_OF_SEREN_8780,
        NpcID.MEMORY_OF_SEREN_8781,
        NpcID.MEMORY_OF_SEREN_8782,
        NpcID.MEMORY_OF_SEREN_8783,
        NpcID.MEMORY_OF_SEREN_8784
    ),
    FRAGMENT_OF_SEREN(
        200,
        LightManager.Alignment.CENTER,
        500,
        17.5f,
        rgb(187, 153, 255),
        LightManager.LightType.PULSE,
        3200,
        10,
        NpcID.FRAGMENT_OF_SEREN,
        NpcID.FRAGMENT_OF_SEREN_8919,
        NpcID.FRAGMENT_OF_SEREN_8920
    ),  // The Gauntlet
    CRYSTALLINE_HUNLLEF(
        200,
        LightManager.Alignment.CENTER,
        800,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        9021,
        NpcID.CRYSTALLINE_HUNLLEF_9022,
        NpcID.CRYSTALLINE_HUNLLEF_9023,
        NpcID.CRYSTALLINE_HUNLLEF_9024
    ),
    CRYSTALLINE_BAT(
        200,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_BAT
    ),
    CRYSTALLINE_RAT(
        40,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_RAT
    ),
    CRYSTALLINE_SPIDER(
        20,
        LightManager.Alignment.CENTER,
        300,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_SPIDER
    ),
    CRYSTALLINE_DRAGON(
        80,
        LightManager.Alignment.CENTER,
        600,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_DRAGON
    ),
    CRYSTALLINE_BEAR(
        80,
        LightManager.Alignment.CENTER,
        500,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_BEAR
    ),
    CRYSTALLINE_DARK_BEAST(
        80,
        LightManager.Alignment.CENTER,
        600,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_DARK_BEAST
    ),
    CRYSTALLINE_SCORPION(
        30,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_SCORPION
    ),
    CRYSTALLINE_UNICORN(
        70,
        LightManager.Alignment.CENTER,
        500,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_UNICORN
    ),
    CRYSTALLINE_WOLF(
        40,
        LightManager.Alignment.CENTER,
        500,
        12.5f,
        rgb(0, 255, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CRYSTALLINE_WOLF
    ),  // Corrupted Gauntlet
    CORRUPTED_HUNLLEF(
        200,
        LightManager.Alignment.CENTER,
        800,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_HUNLLEF,
        NpcID.CORRUPTED_HUNLLEF_9036,
        NpcID.CORRUPTED_HUNLLEF_9037,
        NpcID.CORRUPTED_HUNLLEF_9038
    ),
    CORRUPTED_BAT(
        200,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_BAT
    ),
    CORRUPTED_RAT(
        40,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_RAT
    ),
    CORRUPTED_SPIDER(
        20,
        LightManager.Alignment.CENTER,
        300,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_SPIDER
    ),
    CORRUPTED_DRAGON(
        80,
        LightManager.Alignment.CENTER,
        600,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_DRAGON
    ),
    CORRUPTED_BEAR(
        80,
        LightManager.Alignment.CENTER,
        500,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_BEAR
    ),
    CORRUPTED_DARK_BEAST(
        80,
        LightManager.Alignment.CENTER,
        600,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_DARK_BEAST
    ),
    CORRUPTED_SCORPION(
        30,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_SCORPION
    ),
    CORRUPTED_UNICORN(
        70,
        LightManager.Alignment.CENTER,
        500,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_UNICORN
    ),
    CORRUPTED_WOLF(
        40,
        LightManager.Alignment.CENTER,
        500,
        12.5f,
        rgb(255, 0, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        NpcID.CORRUPTED_WOLF
    ),  // Cerberus
    CERBERUS(
        100,
        LightManager.Alignment.CENTER,
        800,
        30f,
        rgb(255, 208, 54),
        LightManager.LightType.PULSE,
        5000,
        20,
        NpcID.CERBERUS,
        NpcID.CERBERUS_5863,
        NpcID.CERBERUS_5866
    ),  // Tempoross
    TEMPOROSS(
        250,
        LightManager.Alignment.CENTER,
        800,
        17.5f,
        rgb(0, 255, 255),
        LightManager.LightType.PULSE,
        3200,
        20,
        NpcID.TEMPOROSS
    ),
    TEMPOROSS_WHIRLPOOL(
        -30,
        LightManager.Alignment.CENTER,
        500,
        17.5f,
        rgb(0, 255, 255),
        LightManager.LightType.PULSE,
        3200,
        20,
        NpcID.TEMPOROSS_10574,
        10573
    ),
    TEMPOROSS_SPIRIT_POOL(
        5,
        LightManager.Alignment.CENTER,
        500,
        17.5f,
        rgb(0, 255, 255),
        LightManager.LightType.PULSE,
        3200,
        20,
        NpcID.SPIRIT_POOL
    ),  // Morytania

    // Hallowed Sepulchre
    CROSSBOWMAN_STATUE_BOLT(
        220,
        LightManager.Alignment.CENTER,
        400,
        10.0f,
        rgb(0, 190, 252),
        LightManager.LightType.STATIC,
        0,
        0,
        9672
    ),
    CROSSBOWMAN_STATUE_BOLT2(
        220,
        LightManager.Alignment.CENTER,
        400,
        4f,
        rgb(130, 224, 255),
        LightManager.LightType.STATIC,
        0,
        0,
        9673
    ),
    CROSSBOWMAN_STATUE_BOLT3(
        220,
        LightManager.Alignment.CENTER,
        400,
        4f,
        rgb(252, 214, 0),
        LightManager.LightType.STATIC,
        0,
        0,
        9674
    ),  // Theatre of Blood
    NYCOLAS_HAGIOS_SMALL(
        5,
        LightManager.Alignment.CENTER,
        300,
        10.0f,
        rgb(0, 200, 255),
        LightManager.LightType.FLICKER,
        0,
        40,
        8344
    ),
    NYCOLAS_HAGIOS_MEDIUM(
        30,
        LightManager.Alignment.CENTER,
        500,
        10.0f,
        rgb(0, 200, 255),
        LightManager.LightType.FLICKER,
        0,
        40,
        8347,
        8383
    ),
    NYCOLAS_VASILIAS(
        30,
        LightManager.Alignment.CENTER,
        1000,
        12.5f,
        rgb(0, 200, 255),
        LightManager.LightType.FLICKER,
        0,
        40,
        8356
    ),  // Zanaris
    ZANARIS_FAIRY(
        200,
        LightManager.Alignment.CENTER,
        200,
        15.0f,
        rgb(255, 255, 255),
        LightManager.LightType.PULSE,
        4500,
        10,
        NpcID.CHAELDAR,
        NpcID.FAIRY_QUEEN,
        NpcID.FAIRY_NUFF,
        NpcID.FAIRY_GODFATHER,
        NpcID.FAIRY_QUEEN_1842,
        NpcID.FAIRY_VERY_WISE,
        NpcID.FAIRY,
        NpcID.FAIRY_1849,
        NpcID.FAIRY_1850,
        NpcID.FAIRY_1851,
        NpcID.FAIRY_2829,
        NpcID.FAIRY_SHOP_KEEPER,
        NpcID.FAIRY_SHOP_ASSISTANT,
        NpcID.BANKER_3092,
        NpcID.FAIRY_3204,
        NpcID.FAIRY_AERYKA,
        NpcID.COORDINATOR,
        NpcID.FAIRY_NUFF_5836,
        NpcID.FAIRY_GODFATHER_5837,
        NpcID.SLIM_LOUIE,
        NpcID.FAT_ROCCO,
        NpcID.FAIRY_CHEF,
        NpcID.FAIRY_FIXIT,
        NpcID.FAIRY_7748
    ),  // Arceuus spellbook
    GHOSTLY_THRALL(
        80,
        LightManager.Alignment.CENTER,
        400,
        15.0f,
        rgb(0, 100, 255),
        LightManager.LightType.FLICKER,
        0,
        10,
        NpcID.LESSER_GHOSTLY_THRALL,
        NpcID.GREATER_GHOSTLY_THRALL,
        NpcID.SUPERIOR_GHOSTLY_THRALL
    ),
    SKELETAL_THRALL(
        80,
        LightManager.Alignment.CENTER,
        400,
        15.0f,
        rgb(144, 245, 66),
        LightManager.LightType.FLICKER,
        0,
        10,
        NpcID.LESSER_SKELETAL_THRALL,
        NpcID.GREATER_SKELETAL_THRALL,
        NpcID.SUPERIOR_SKELETAL_THRALL
    ),
    ZOMBIE_THRALL(
        80,
        LightManager.Alignment.CENTER,
        400,
        15.0f,
        rgb(255, 0, 0),
        LightManager.LightType.FLICKER,
        0,
        10,
        NpcID.LESSER_ZOMBIFIED_THRALL,
        NpcID.GREATER_ZOMBIFIED_THRALL,
        NpcID.SUPERIOR_ZOMBIFIED_THRALL
    ),  // Chambers of Xeric
    COX_GLOWING_CRYSTAL(
        180,
        LightManager.Alignment.CENTER,
        900,
        15.0f,
        rgb(76, 0, 255),
        LightManager.LightType.PULSE,
        2400,
        20,
        7568
    ),
    VASA_NISTIRIO(
        300,
        LightManager.Alignment.CENTER,
        1200,
        15.0f,
        rgb(76, 0, 255),
        LightManager.LightType.PULSE,
        2400,
        30,
        NpcID.VASA_NISTIRIO,
        NpcID.VASA_NISTIRIO_7567
    ),
    TEKTON(
        100,
        LightManager.Alignment.CENTER,
        600,
        15.0f,
        rgb(255, 162, 41),
        LightManager.LightType.STATIC,
        2400,
        0,
        NpcID.TEKTON,
        NpcID.TEKTON_7541,
        NpcID.TEKTON_7542,
        NpcID.TEKTON_7545
    ),
    TEKTON_ENRAGED(
        100,
        LightManager.Alignment.CENTER,
        600,
        20.0f,
        rgb(255, 95, 41),
        LightManager.LightType.STATIC,
        2400,
        0,
        NpcID.TEKTON_ENRAGED,
        NpcID.TEKTON_ENRAGED_7544
    ),
    VANGUARD(
        20,
        LightManager.Alignment.CENTER,
        600,
        15.0f,
        rgb(255, 162, 41),
        LightManager.LightType.STATIC,
        2400,
        0,
        NpcID.VANGUARD,
        NpcID.VANGUARD_7526,
        NpcID.VANGUARD_7527,
        NpcID.VANGUARD_7528,
        NpcID.VANGUARD_7529
    ),
    JEWELLED_CRAB_GREEN(
        60,
        LightManager.Alignment.CENTER,
        300,
        15.0f,
        rgb(128, 255, 0),
        LightManager.LightType.PULSE,
        2400,
        20,
        NpcID.JEWELLED_CRAB_GREEN
    ),
    JEWELLED_CRAB_RED(
        60,
        LightManager.Alignment.CENTER,
        300,
        15.0f,
        rgb(255, 0, 0),
        LightManager.LightType.PULSE,
        2400,
        20,
        NpcID.JEWELLED_CRAB_RED
    ),
    JEWELLED_CRAB_BLUE(
        60,
        LightManager.Alignment.CENTER,
        300,
        15.0f,
        rgb(0, 255, 255),
        LightManager.LightType.PULSE,
        2400,
        20,
        NpcID.JEWELLED_CRAB_BLUE
    ),  // Nightmare of Ashihama
    THE_NIGHTMARE_INACTIVE(
        100,
        LightManager.Alignment.CENTER,
        1200,
        15.0f,
        rgb(255, 0, 166),
        LightManager.LightType.PULSE,
        1950,
        20,
        NpcID.THE_NIGHTMARE_9461,
        NpcID.THE_NIGHTMARE_9462,
        NpcID.THE_NIGHTMARE_9463,
        NpcID.THE_NIGHTMARE_9464
    ),
    FIRE_GIANT(
        370,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(255, 124, 0),
        LightManager.LightType.FLICKER,
        0,
        20,
        NpcID.FIRE_GIANT,
        NpcID.FIRE_GIANT_2076,
        NpcID.FIRE_GIANT_2077,
        NpcID.FIRE_GIANT_2078,
        NpcID.FIRE_GIANT_2079,
        NpcID.FIRE_GIANT_2080,
        NpcID.FIRE_GIANT_2081,
        NpcID.FIRE_GIANT_2082,
        NpcID.FIRE_GIANT_2083,
        NpcID.FIRE_GIANT_2084,
        NpcID.FIRE_GIANT_7251,
        NpcID.FIRE_GIANT_7252
    ),  // Pest Control
    PEST_CONTROL_PURPLE_PORTAL(
        120,
        LightManager.Alignment.CENTER,
        400,
        15.0f,
        rgb(150, 75, 255),
        LightManager.LightType.PULSE,
        2000,
        25,
        NpcID.PORTAL,
        NpcID.PORTAL_1743,
        NpcID.PORTAL_1747,
        NpcID.PORTAL_1751
    ),
    PEST_CONTROL_BLUE_PORTAL(
        120,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(0, 175, 255),
        LightManager.LightType.PULSE,
        2000,
        25,
        NpcID.PORTAL_1740,
        NpcID.PORTAL_1744,
        NpcID.PORTAL_1748,
        NpcID.PORTAL_1752
    ),
    PEST_CONTROL_YELLOW_PORTAL(
        120,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(230, 255, 90),
        LightManager.LightType.PULSE,
        2000,
        25,
        NpcID.PORTAL_1741,
        NpcID.PORTAL_1745,
        NpcID.PORTAL_1749,
        NpcID.PORTAL_1753
    ),
    PEST_CONTROL_RED_PORTAL(
        120,
        LightManager.Alignment.CENTER,
        400,
        12.5f,
        rgb(255, 0, 90),
        LightManager.LightType.PULSE,
        2000,
        25,
        NpcID.PORTAL_1742,
        NpcID.PORTAL_1746,
        NpcID.PORTAL_1750,
        NpcID.PORTAL_1754
    ),
    PEST_CONTROL_KNIGHT(
        15,
        LightManager.Alignment.CENTER,
        200,
        7.5f,
        rgb(255, 0, 30),
        LightManager.LightType.PULSE,
        1500,
        10,
        NpcID.VOID_KNIGHT_2950,
        NpcID.VOID_KNIGHT_2951,
        NpcID.VOID_KNIGHT_2952,
        NpcID.VOID_KNIGHT_2953
    );

    companion object {
        private var LIGHTS: Map<Int, NpcLight>? = null
        fun find(id: Int): NpcLight? {
            return LIGHTS!![id]
        }

        init {
            val builder = ImmutableMap.Builder<Int, NpcLight>()
            for (npcLight in values()) {
                for (id in npcLight.id) {
                    builder.put(id, npcLight)
                }
            }
            LIGHTS = builder.build()
        }
    }
}